<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sophia Salas">
<meta name="dcterms.date" content="2026-05-14">

<title>Poisson Regression and Maximum Likelihood Estimation – Sophia Salas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b9729af4fc7702d2683b6aca8683021a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sophia Salas</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../quotes.html"> 
<span class="menu-text">Quotes</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#exploring-the-data" id="toc-exploring-the-data" class="nav-link" data-scroll-target="#exploring-the-data">Exploring the Data</a></li>
  <li><a href="#what-does-the-data-show" id="toc-what-does-the-data-show" class="nav-link" data-scroll-target="#what-does-the-data-show">What Does the Data Show?</a></li>
  </ul></li>
  <li><a href="#a-simple-poisson-model-via-maximum-likelihood" id="toc-a-simple-poisson-model-via-maximum-likelihood" class="nav-link" data-scroll-target="#a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</a>
  <ul class="collapse">
  <li><a href="#coding-the-log-likelihood-function" id="toc-coding-the-log-likelihood-function" class="nav-link" data-scroll-target="#coding-the-log-likelihood-function">Coding the Log-Likelihood Function</a>
  <ul class="collapse">
  <li><a href="#plotting-the-log-likelihood-function" id="toc-plotting-the-log-likelihood-function" class="nav-link" data-scroll-target="#plotting-the-log-likelihood-function">Plotting the Log-Likelihood Function</a></li>
  </ul></li>
  <li><a href="#a-little-mathematical-fun---finding-the-mle-analytically" id="toc-a-little-mathematical-fun---finding-the-mle-analytically" class="nav-link" data-scroll-target="#a-little-mathematical-fun---finding-the-mle-analytically">A Little Mathematical Fun - Finding the MLE Analytically</a></li>
  <li><a href="#finding-the-mle-numerically" id="toc-finding-the-mle-numerically" class="nav-link" data-scroll-target="#finding-the-mle-numerically">Finding the MLE Numerically</a></li>
  </ul></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression">Poisson Regression</a>
  <ul class="collapse">
  <li><a href="#updating-the-log-likelihood-function-for-poisson-regression" id="toc-updating-the-log-likelihood-function-for-poisson-regression" class="nav-link" data-scroll-target="#updating-the-log-likelihood-function-for-poisson-regression">Updating the Log-Likelihood Function for Poisson Regression</a></li>
  <li><a href="#finding-mle-for-poisson-regression" id="toc-finding-mle-for-poisson-regression" class="nav-link" data-scroll-target="#finding-mle-for-poisson-regression">Finding MLE for Poisson Regression</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results">Interpreting the Results</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#the-effect-of-blueprintys-software" id="toc-the-effect-of-blueprintys-software" class="nav-link" data-scroll-target="#the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</a>
  <ul class="collapse">
  <li><a href="#our-results" id="toc-our-results" class="nav-link" data-scroll-target="#our-results">Our Results</a></li>
  </ul></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key Takeaways</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression and Maximum Likelihood Estimation</h1>
<p class="subtitle lead">A Case Study of Blueprinty’s Software and Patent Awards</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sophia Salas </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 14, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p><strong>Blueprinty</strong> is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty’s software are more successful in getting their patent applications approved. The ideal dataset for studying such an effect would include each firm’s success rate before using Blueprinty’s software and after using it, but no such data is available. Instead, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm’s number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty’s software. The marketing team wants to use this data to argue that firms using Blueprinty’s software are more successful in getting their patent applications approved.</p>
<p>However, this is a non-trivial claim to evaluate: Blueprinty’s customers are not selected at random, so any raw difference in patent counts could reflect characteristics of the firms (e.g., age, region) rather than the software itself. Why is this non-trivial? Because if customers tend to be older firms or firms located in regions with more patent activity, then they may have higher patent counts regardless of the software. To make a convincing argument, we need to account for these confounding factors and isolate the effect of using Blueprinty’s software on patent success.</p>
<!-- Write a short introduction for the reader that sets the scene. Cover the following points in your own words:

- Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office.

- Their marketing team would like to make the claim that patent applicants using Blueprinty's software are more successful in getting their patent applications approved.

- The ideal dataset for studying such an effect would include each firm's success rate before using Blueprinty's software and after using it, but no such data is available.

- Instead, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm's number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty's software.

- The marketing team wants to use this data to argue that firms using Blueprinty's software are more successful in getting their patent applications approved. Explain to the reader why this is a non-trivial claim to evaluate: Blueprinty's customers are not selected at random, so any raw difference in patent counts could reflect characteristics of the firms (e.g., age, region) rather than the software itself. -->
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h2>
<p>We can construct two distribution histograms showing the number of patents awarded to customers and non-customers, and we can report the means of each group. This will give us a preliminary sense of whether there is an association between being a customer and having more patents, but we will need to be careful in interpreting these results because they do not account for potential confounding factors.</p>
<div id="5b72992b" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-3-output-1.png" width="965" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-does-the-data-show" class="level2">
<h2 class="anchored" data-anchor-id="what-does-the-data-show">What Does the Data Show?</h2>
<p>If we compare the two histograms, we are able to compare the means of the two groups. We see that the mean number of patents for customers is 4.133, while the mean number of patents for non-customers is 3.47. This suggests that customers of Blueprinty’s software have a higher average number of patents than non-customers. However, this raw difference does not account for potential confounding factors such as firm age and regional location, which may also influence patent counts.</p>
<p>Blueprinty’s customers are not selected at randoms, it may be important to account for systematic differences in firm age and regional location between customers and non-customers. To explore this, we can compare the distribution of regions by customer status and compare histograms of firm age by customer status. This will help us understand whether there are systematic differences in these characteristics between customers and non-customers, which could confound our analysis of the effect of using Blueprinty’s software on patent counts.</p>
<section id="histograms-of-region-by-customer-status" class="level4">
<h4 class="anchored" data-anchor-id="histograms-of-region-by-customer-status">Histograms of Region by Customer Status</h4>
<div id="c8e315b0" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>region      Midwest  Northeast  Northwest  South  Southwest
iscustomer                                                 
0               187        273        158    156        245
1                37        328         29     35         52</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-5-output-2.png" width="816" height="503" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Our preliminary analysis of the distribution of regions by customer status shows that there are some differences in regional location between customers and non-customers. For example, a higher proportion of customers are located in the Northeast and South regions compared to non-customers, while a higher proportion of non-customers are located in the Northwest region compared to customers. These regional differences could potentially confound our analysis of the effect of using Blueprinty’s software on patent counts, as certain regions may have more patent activity than others. Therefore, it is important to account for these regional differences in our subsequent analysis.</p>
</section>
<section id="histograms-of-firm-age-by-customer-status" class="level4">
<h4 class="anchored" data-anchor-id="histograms-of-firm-age-by-customer-status">Histograms of Firm Age by Customer Status</h4>
<div id="095e023c" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-6-output-1.png" width="1142" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Our preliminary analysis of the distribution of firm age by customer status shows that there are some differences in age between customers and non-customers. Customers tend to be older than the average non-customer with an average age of 26.9 compared to the non-customer with an average age of 26.1. There are a smaller number of firms for Blueprinty than non-customers.</p>
<!-- ::: {.callout-note}
- Read in the data from `blueprinty.csv`.

- Compare histograms of the number of patents by customer status (customers vs non-customers) and report the means of each group. Place the two histograms side by side with consistent x-axis scales so they are easy to compare. After the plots, write a few sentences describing what you observe.

- Blueprinty's customers are not selected at random. It may be important to account for systematic differences in firm age and regional location between customers and non-customers. Compare the distribution of regions by customer status, and compare histograms of firm age by customer status. After each comparison, write a few sentences describing what you observe and explain to the reader why these differences matter for the analysis that follows.
:::
 -->
</section>
</section>
</section>
<section id="a-simple-poisson-model-via-maximum-likelihood" class="level1">
<h1>A Simple Poisson Model via Maximum Likelihood</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>Poisson distribution</strong> is a discrete probability distribution that models the number of events occurring within a fixed interval of time or space, given a constant average rate of occurrence.</p>
</div>
</div>
<p>It is defined by a single parameter <span class="math inline">\(\lambda\)</span>, which represents the average number of events in the interval. The probability mass function (PMF) of the Poisson distribution is given by <span class="math display">\[f(Y|\lambda) = \frac{e^{-\lambda}\lambda^{Y}}{Y!}\]</span> where <span class="math inline">\(Y\)</span> is the number of events (e.g., patents awarded) and <span class="math inline">\(Y!\)</span> is the factorial of <span class="math inline">\(Y\)</span>. The Poisson distribution is often used for modeling count data, especially when the counts are non-negative integers and the mean is equal to the variance. In our case, the number of patents awarded to each firm over the last 5 years is a count variable, making the Poisson distribution a natural choice for modeling this outcome.</p>
<p>Now, let’s start the likelihood and log-likelihood derivation for a simple Poisson model where every firm has the same patent rate <span class="math inline">\(\lambda\)</span>.</p>
<p>We will show the derivation step by step to demonstrate how the joint likelihood is built from the iid assumption and how the log-likelihood simplifies.</p>
<p>Log Likelihood Derivation:</p>
<p>We start with the PMF (probability mass function) of the Poisson distribution for a single observation <span class="math inline">\(Y_i\)</span>: <span class="math display">\[
f(Y|\lambda) = \frac{e^{-\lambda}\lambda^{Y}}{Y!}
\]</span></p>
<p>Because the observations are independents, the joint likelihood <span class="math inline">\(L(\lambda)\)</span> is the proudct of the inidiviudal probability mass functions for all <span class="math inline">\(n\)</span> observations: <span class="math display">\[
L(\lambda) = \prod_{i=1}^{n} f(Y_i|\lambda) = \prod_{i=1}^{n} \frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!} = e^{-n\lambda} \lambda^{\sum_{i=1}^{n} Y_i} \prod_{i=1}^{n} \frac{1}{Y_i!}
\]</span></p>
<section id="a-little-note-on-the-iid-assumption" class="level4">
<h4 class="anchored" data-anchor-id="a-little-note-on-the-iid-assumption">A little note on the iid assumption:</h4>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>IID</strong> is a common assumption in statistical modeling that stands for “independent and identically distributed.” It means that the observations (in this case, the number of patents awarded to each firm) are independent of each other and come from the same probability distribution (in this case, a Poisson distribution with parameter <span class="math inline">\(\lambda\)</span>). This assumption allows us to write the joint likelihood as a product of individual likelihoods for each observation.</p>
</div>
</div>
<p>If we expand the product across n terms, we get: <span class="math display">\[
L(\lambda) =
\frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!} * \frac{e^{-\lambda}\lambda^{Y_2}}{Y_2!} * \cdots * \frac{e^{-\lambda}\lambda^{Y_n}}{Y_n!}
\]</span></p>
<p>Multiplying <span class="math inline">\(e^{-\lambda}\)</span> across n terms gives us <span class="math inline">\(e^{-n\lambda}\)</span>, and multiplying <span class="math inline">\(\lambda^{Y_i}\)</span> across n terms gives us <span class="math inline">\(\lambda^{\sum_{i=1}^{n} Y_i}\)</span>. The product of the factorial terms is <span class="math inline">\(\prod_{i=1}^{n} \frac{1}{Y_i!}\)</span>.</p>
<p>This gives us the joint likelihood function for the Poisson model. <span class="math display">\[
L(\lambda) = \frac{e^{-n\lambda} \lambda\prod_{i=1}^{n} Y_i}{\prod_{i=1}^{n} Y_i!}
\]</span></p>
<p>To get us from the join likelihood to the log-likelihood, we take the natural logarithm of the likelihood function: <span class="math display">\[
\ell(\lambda) = \ln(\frac{e^{-n\lambda} \lambda\prod_{i=1}^{n} Y_i}{\prod_{i=1}^{n} Y_i!})
\]</span></p>
<p>Using properties of logarithms, we can simplify this expression: <span class="math display">\[
\ell(\lambda) = \ln(e^{-n\lambda}) + \ln(\lambda^{\sum_{i=1}^{n} Y_i}) - \ln(\prod_{i=1}^{n} Y_i!)
\]</span> By using the power rule of logarithms, we can further simplify the second term to retrive the final log-likelihood function. ### Final Log-Likelihood Function: <span class="math display">\[
\ell(\lambda) = -n\lambda + \ln(\lambda) \sum_{i=1}^{n} Y_i - \sum_{i=1}^{n} \ln(Y_i!)
\]</span></p>
</section>
<section id="coding-the-log-likelihood-function" class="level2">
<h2 class="anchored" data-anchor-id="coding-the-log-likelihood-function">Coding the Log-Likelihood Function</h2>
<p>Now that we know how to get derive the log-likelihood function, we can code it in Python. Below is an example of how to implement the Poisson log-likelihood function in Python:</p>
<div id="89249c30" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.special <span class="im">as</span> special</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_loglikelihood(lambda_, Y):</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># n is the number of observations we get by taking the length of the Y vector</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(Y)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># The log-likelihood function is derived from the likelihood function we derived above, and we use the properties of logarithms to simplify it. We also use scipy's special.factorial function to compute the factorial of Y.</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    log_likelihood <span class="op">=</span> <span class="op">-</span>n <span class="op">*</span> lambda_ <span class="op">+</span> np.<span class="bu">sum</span>(Y) <span class="op">*</span> np.log(lambda_) <span class="op">-</span> np.<span class="bu">sum</span>(special.gammaln(Y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> log_likelihood</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This function takes in a scalar <span class="math inline">\(\lambda\)</span> and a vector of observed counts <span class="math inline">\(Y\)</span>, and it computes the log-likelihood of the Poisson model given those inputs. The function first calculates the number of observations <span class="math inline">\(n\)</span> from the length of the <span class="math inline">\(Y\)</span> vector, and then it uses the formula for the log-likelihood that we derived earlier to compute the log-likelihood value. The <code>scipy.special.gammaln</code> function is used to compute the logarithm of the factorial of each element in <span class="math inline">\(Y\)</span> efficiently.</p>
<section id="plotting-the-log-likelihood-function" class="level3">
<h3 class="anchored" data-anchor-id="plotting-the-log-likelihood-function">Plotting the Log-Likelihood Function</h3>
<p>Now that we have our log-likelihood function coded, we can plot it to visualize how the log-likelihood changes with different values of <span class="math inline">\(\lambda\)</span>. We will use the observed number of patents as the input for <span class="math inline">\(Y\)</span> and plot <span class="math inline">\(\lambda\)</span> on the horizontal axis and the log-likelihood on the vertical axis.</p>
<div id="0fd48f06" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-8-output-1.png" width="844" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="a-little-mathematical-fun---finding-the-mle-analytically" class="level2">
<h2 class="anchored" data-anchor-id="a-little-mathematical-fun---finding-the-mle-analytically">A Little Mathematical Fun - Finding the MLE Analytically</h2>
<p>If we take the first derivative of the log-likelihood function with respect to <span class="math inline">\(\lambda\)</span>, set it equal to zero, and solve for <span class="math inline">\(\lambda\)</span>, we can find the maximum likelihood estimator (MLE) for <span class="math inline">\(\lambda\)</span>. The MLE turns out to be <span class="math inline">\(\hat\lambda_{\text{MLE}} = \bar{Y}\)</span>, which is the sample mean of the observed counts. This result makes intuitive sense because the mean of a Poisson distribution is equal to its parameter <span class="math inline">\(\lambda\)</span>, so it is reasonable that the MLE for <span class="math inline">\(\lambda\)</span> would be the sample mean of the observed counts.</p>
<p><span class="math display">\[
\frac{d}{d\lambda}\ell(\lambda) = -n + \frac{1}{\lambda} \sum_{i=1}^{n} Y_i - \sum_{i=1}^{n} \frac{1}{Y_i!} \frac{d}{d\lambda}(Y_i!)
\]</span></p>
<p>Intermediate steps: 1. The derivative of the first term <span class="math inline">\(-n\lambda\)</span> with respect to <span class="math inline">\(\lambda\)</span> is simply <span class="math inline">\(-n\)</span>. 2. The derivative of the second term <span class="math inline">\(\ln(\lambda) \sum_{i=1}^{n} Y_i\)</span> with respect to <span class="math inline">\(\lambda\)</span> is <span class="math inline">\(\frac{1}{\lambda} \sum_{i=1}^{n} Y_i\)</span>, using the chain rule of differentiation. 3. The derivative of the third term <span class="math inline">\(-\sum_{i=1}^{n} \ln(Y_i!)\)</span> with respect to <span class="math inline">\(\lambda\)</span> is zero because it does not depend on <span class="math inline">\(\lambda\)</span>.</p>
<p>Solving this equation for <span class="math inline">\(\lambda\)</span> gives us the MLE: <span class="math display">\[
\hat\lambda_{\text{MLE}} = \frac{1}{n} \sum_{i=1}^{n} Y_i = \bar{Y}
\]</span></p>
<p>This means that the MLE for <span class="math inline">\(\lambda\)</span> is simply the average number of patents awarded across all firms in the dataset.</p>
</section>
<section id="finding-the-mle-numerically" class="level2">
<h2 class="anchored" data-anchor-id="finding-the-mle-numerically">Finding the MLE Numerically</h2>
<p>Now we can find the MLE numerically by maximizing our log-likelihood function using Python’s <code>scipy.optimize</code> module. We will use the <code>minimize</code> function to find the value of <span class="math inline">\(\lambda\)</span> that maximizes the log-likelihood. Since <code>minimize</code> minimizes a function, we will minimize the negative log-likelihood instead.</p>
<div id="c36a754f" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to minimize the negative log-likelihood</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> negative_loglikelihood(lambda_):</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>poisson_loglikelihood(lambda_, Y)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Minimize to find lambda that minimizes the negative log-likelihood</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(negative_loglikelihood, x0 <span class="op">=</span> np.mean(Y), bounds<span class="op">=</span>[(<span class="fl">0.1</span>, <span class="va">None</span>)])</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Start at the sample mean and ensure lambda is positive</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>mle_lambda <span class="op">=</span> result.x[<span class="dv">0</span>]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MLE for lambda: </span><span class="sc">{</span>mle_lambda<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample mean (MLE): </span><span class="sc">{</span>np<span class="sc">.</span>mean(Y)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>MLE for lambda: 3.6846666666666668
Sample mean (MLE): 3.6846666666666668</code></pre>
</div>
</div>
<p>We see that the numerical MLE for <span class="math inline">\(\lambda\)</span> is very close to the sample mean of <span class="math inline">\(Y\)</span>, which confirms our analytical result that the MLE for <span class="math inline">\(\lambda\)</span> in a Poisson model is the sample mean of the observed counts. This is because the log-likelihood function is maximized at the point where <span class="math inline">\(\lambda\)</span> equals the average number of patents awarded, which is consistent with the properties of the Poisson distribution.</p>
<!--
::: {.callout-note}
- The outcome variable is a count — the number of patents awarded to each firm over the last 5 years — so we can model it as a draw from a Poisson distribution. Write a short introduction explaining this modeling choice to the reader: counts cannot be negative and must be integer-valued, so the Normal distribution is a poor fit, and the Poisson distribution is the natural starting point for non-negative integer outcomes.
:::

- Write down the likelihood and log-likelihood for $Y \sim \text{Poisson}(\lambda)$, using the fact that

$$
f(Y|\lambda) = \frac{e^{-\lambda}\lambda^{Y}}{Y!}
$$

  Show the derivation step by step so the reader can follow how the joint likelihood is built from the iid assumption and how the log-likelihood simplifies. -->
<!-- - Code the log-likelihood function in the language of your choice. It should be a function of $\lambda$ and $Y$. For example, in R:

    ```r
    poisson_loglikelihood <- function(lambda, Y){
       ...
    }
    ``` -->
<!-- - Use your function to plot $\lambda$ on the horizontal axis and the log-likelihood on the vertical axis for a range of values of $\lambda$, using the observed number of patents as the input for $Y$. After the plot, write a sentence or two explaining what the curve shows and how to "read" the MLE off it visually. -->
<!-- - If you're feeling mathematical, take the first derivative of the log-likelihood, set it equal to zero, and solve for $\lambda$. You will find $\hat\lambda_{\text{MLE}} = \bar{Y}$, which "feels right" because the mean of a Poisson distribution is $\lambda$. -->
<!-- - Find the MLE numerically by maximizing your log-likelihood function with R's `optim()` or Python's `sp.optimize()`. Compare your numerical answer to the sample mean — they should be (nearly) identical, and you should explain to the reader why. -->
</section>
</section>
<section id="poisson-regression" class="level1">
<h1>Poisson Regression</h1>
<p>Now we have a simple Poisson model where every firm has the same patent rate <span class="math inline">\(\lambda\)</span>. However, we know that firms differ in their characteristics (e.g., age, region, customer status), and these characteristics likely influence their patent counts. To account for this heterogeneity, we can extend our model to a Poisson regression model where each firm’s rate parameter <span class="math inline">\(\lambda_i\)</span> depends on its own characteristics. <span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i) \qquad \text{where} \qquad \lambda_i = \exp(X_i'\beta)
\]</span></p>
<section id="why-do-we-do-this" class="level4">
<h4 class="anchored" data-anchor-id="why-do-we-do-this">Why Do We Do This?</h4>
<p>Instead of assuming every firm has the same patent rate <span class="math inline">\(\lambda\)</span>, we now let <span class="math inline">\(\lambda\)</span> vary across firms as a function of age, region, and customer status. This allows us to capture the influence of these characteristics on patent counts and to isolate the effect of being a Blueprinty customer while controlling for other factors. We use <span class="math inline">\(\exp(\cdot)\)</span> as the inverse link function because <span class="math inline">\(\lambda_i\)</span> must be positive (since it represents a rate), but <span class="math inline">\(X_i'\beta\)</span> can be any real number. The exponential function ensures that <span class="math inline">\(\lambda_i\)</span> stays on the positive real line, which is necessary for the Poisson model to be valid. This is a key feature of Poisson regression: it models the log of the expected count as a linear function of the predictors, which allows for a multiplicative effect of the predictors on the expected count.</p>
</section>
<section id="updating-the-log-likelihood-function-for-poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="updating-the-log-likelihood-function-for-poisson-regression">Updating the Log-Likelihood Function for Poisson Regression</h2>
<p>Now we can update our log-likelihood function to take in a covariate matrix <span class="math inline">\(X\)</span> and a parameter vector <span class="math inline">\(\beta\)</span> in place of the scalar <span class="math inline">\(\lambda\)</span>. The log-likelihood for the Poisson regression model can be written as: <span class="math display">\[
\ell(\beta) = \sum_{i=1}^{n} \left( -\exp(X_i'\beta) + Y_i X_i'\beta - \ln(Y_i!) \right)
\]</span></p>
<p>This function takes into account the fact that each firm’s rate parameter <span class="math inline">\(\lambda_i\)</span> is now a function of its characteristics through the linear predictor <span class="math inline">\(X_i'\beta\)</span>. The first term <span class="math inline">\(-\exp(X_i'\beta)\)</span> represents the contribution of the expected count, the second term <span class="math inline">\(Y_i X_i'\beta\)</span> represents the contribution of the observed count, and the third term <span class="math inline">\(-\ln(Y_i!)\)</span> is the same as before, representing the contribution of the factorial term in the Poisson PMF. We can implement this log-likelihood function in Python as follows:</p>
<div id="9f8a5cc1" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_loglikelihood(beta, Y, X):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Linear predictor X * beta</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    lin_pred <span class="op">=</span> np.dot(X, beta)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Expected mean: lambda = exp(X * beta)</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    expected_count <span class="op">=</span> np.exp(lin_pred)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Log-likelihood</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    log_likelihood <span class="op">=</span> np.<span class="bu">sum</span>(<span class="op">-</span>expected_count <span class="op">+</span> Y <span class="op">*</span> lin_pred <span class="op">-</span> special.gammaln(Y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> log_likelihood</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We will construct <span class="math inline">\(X\)</span> so that the first column is all 1’s (for the intercept), followed by columns for age, age squared, binary indicators for all but one of the regions, and the binary customer variable. We include age squared because the relationship between age and patenting is unlikely to be perfectly linear — it may be that very young firms and very old firms have lower patent counts than middle-aged firms. We must drop one region to avoid perfect collinearity with the intercept; if we included all regions, we would have a situation where the sum of the region indicators equals 1 for every observation, which would make it impossible to estimate the coefficients uniquely.</p>
</section>
<section id="finding-mle-for-poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="finding-mle-for-poisson-regression">Finding MLE for Poisson Regression</h2>
<p>Now we can use <code>scipy.optimize.minimize</code> to find the MLE <span class="math inline">\(\hat\beta\)</span> for the Poisson regression model. We will minimize the negative log-likelihood function, and we will also ask the optimizer to return the Hessian so that we can compute standard errors for the coefficients. The standard errors are the square roots of the diagonal of the negative inverse Hessian.</p>
<div id="c6b7ece0" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 3258.072145
         Iterations: 39
         Function evaluations: 36
         Gradient evaluations: 35
         Hessian evaluations: 34
  Feature  Coefficient  Standard Error
Intercept    -0.508920        0.183179
      Age     0.148619        0.013869
    Age^2    -0.002970        0.000258
Northeast     0.029170        0.043625
Northwest    -0.017575        0.053781
    South     0.056561        0.052662
Southwest     0.050576        0.047198
 Customer     0.207591        0.030895</code></pre>
</div>
</div>
<p>Let’s check our results by fitting the same model Python’s <code>statsmodels.api.GLM()</code>. The coefficient estimates should match closely; the standard errors may differ slightly due to the numerical approximation of the Hessian, which is a common issue when using optimization routines to estimate standard errors. The exact values of the standard errors can be sensitive to the convergence criteria and the numerical precision of the optimization algorithm, so it’s not uncommon to see some discrepancies between different methods of estimation. However, as long as the coefficient estimates are consistent across methods, we can be confident in our findings.</p>
<div id="205fdcd0" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                 1500
Model:                            GLM   Df Residuals:                     1492
Model Family:                 Poisson   Df Model:                            7
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -3258.1
Date:                Sun, 17 May 2026   Deviance:                       2143.3
Time:                        23:47:00   Pearson chi2:                 2.07e+03
No. Iterations:                     5   Pseudo R-squ. (CS):             0.1360
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.5089      0.183     -2.778      0.005      -0.868      -0.150
x1             0.1486      0.014     10.716      0.000       0.121       0.176
x2            -0.0030      0.000    -11.513      0.000      -0.003      -0.002
x3             0.0292      0.044      0.669      0.504      -0.056       0.115
x4            -0.0176      0.054     -0.327      0.744      -0.123       0.088
x5             0.0566      0.053      1.074      0.283      -0.047       0.160
x6             0.0506      0.047      1.072      0.284      -0.042       0.143
x7             0.2076      0.031      6.719      0.000       0.147       0.268
==============================================================================</code></pre>
</div>
</div>
<div id="341a261e" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>  Feature  Manual Coefficient  Manual SE  Statsmodels Coefficient  Statsmodels SE
Intercept           -0.508920   0.183179                -0.508920        0.183179
      Age            0.148619   0.013869                 0.148619        0.013869
    Age^2           -0.002970   0.000258                -0.002970        0.000258
Northeast            0.029170   0.043625                 0.029170        0.043625
Northwest           -0.017575   0.053781                -0.017575        0.053781
    South            0.056561   0.052662                 0.056561        0.052662
Southwest            0.050576   0.047198                 0.050576        0.047198
 Customer            0.207591   0.030895                 0.207591        0.030895</code></pre>
</div>
</div>
<section id="interpreting-the-results" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-results">Interpreting the Results</h3>
<p>Now that we have our coefficient estimates and standard errors, we can interpret the results. Each coefficient represents the log change in the expected count of patents for a one-unit increase in the corresponding predictor, holding all other predictors constant.</p>
<p><strong>Intercept Coefficient</strong>: -0.509; This can be interpreted as the expected log count of patents for a firm with age 0, located in the baseline region (the one we dropped), and not being a customer.</p>
<p><strong>Age Coefficient</strong>: 0.149 ; This suggests that, holding other factors constant, each additional year of age is associated with an increase in the log count of patents. <strong>Age^2 Coefficient</strong>: -0.003 ; This indicates that the relationship between age and patenting is not perfectly linear. <strong>Northeast Region Coefficient</strong>: 0.029; This suggests that firms located in the Northeast region have a higher expected log count of patents compared to the baseline region, holding other factors constant. <strong>Northwest Region Coefficient</strong>: -0.017; This suggests that firms located in the Northwest region have a lower expected log count of patents compared to the baseline region, holding other factors constant. <strong>South Region Coefficient</strong>: 0.05; This suggests that firms located in the South region have a higher expected log count of patents compared to the baseline region, holding other factors constant. <strong>Southwest Region Coefficient</strong>: 0.051; This suggests that firms located in the Southwest region have a higher expected log count of patents compared to the baseline region, holding other factors constant. <strong>Customer Coefficient</strong>: 0.208; This suggests that firms that are customers have a higher expected log count of patents compared to non-customers, holding other factors constant.</p>
<p><strong>A quick check</strong> - are the signs and magnitudes sensible? The positive coefficient for age makes sense, as older firms may have more resources and experience to file patents. The negative coefficient for age squared also makes sense, as the relationship between age and patenting is likely to be non-linear. The regional coefficients suggest that location does matter for patenting activity, which is consistent with what we know about regional differences in innovation. Finally, the positive coefficient for being a customer of Blueprinty’s software suggests that there may be an association between using the software and having more patents, but we will need to be careful in interpreting this result due to potential confounding factors.</p>
<!-- ::: {.callout-note}
- Now extend the simple Poisson model to a Poisson regression model so that each firm's rate parameter depends on its own characteristics:

$$
Y_i \sim \text{Poisson}(\lambda_i) \qquad \text{where} \qquad \lambda_i = \exp(X_i'\beta)
$$

  Write a short introduction explaining this extension to the reader. Instead of assuming every firm has the same patent rate $\lambda$, we now let $\lambda$ vary across firms as a function of age, region, and customer status. Explain why we use $\exp(\cdot)$ as the inverse link: $\lambda_i$ must be positive, but $X_i'\beta$ can be any real number, so the exponential keeps $\lambda_i$ on the positive real line.

- Update your log-likelihood function from the previous section to take in a covariate matrix $X$ and a parameter vector $\beta$ in place of the scalar $\lambda$. For example:

    ```r
    poisson_regression_loglikelihood <- function(beta, Y, X){
       ...
    }
    ``` -->
<!-- - Construct $X$ so that the first column is all 1's (for the intercept), followed by columns for age, age squared, binary indicators for all but one of the regions, and the binary customer variable. Explain to the reader why you include age squared (the relationship between age and patenting is unlikely to be perfectly linear) and why you must drop one region (to avoid perfect collinearity with the intercept). -->
<!-- - Use `optim()` (or `sp.optimize()`) to find the MLE $\hat\beta$, asking the optimizer to also return the Hessian. Use the Hessian to compute standard errors for the coefficients — the standard errors are the square roots of the diagonal of the negative inverse Hessian. Present a table of coefficients and standard errors. -->
<!-- - Check your results by fitting the same model with R's `glm(..., family = poisson)` or Python's `sm.GLM()`. The coefficient estimates should match closely; the standard errors may differ slightly due to the numerical approximation of the Hessian — explain this to the reader. -->
<!-- - Interpret the results. Walk the reader through what each coefficient tells you, paying particular attention to the sign and magnitude of the customer coefficient. Are the signs and magnitudes sensible?
::: -->
</section>
</section>
</section>
<section id="the-effect-of-blueprintys-software" class="level1">
<h1>The Effect of Blueprinty’s Software</h1>
<p>Because the coefficients from the Poisson regression are not the most interpretable as “additional patents,” (we interpreted them as log-rates) we will use our fitted model to construct a more interpretable estimate of the average effect of being a Blueprinty customer on patent counts, holding age and region fixed at their observed values for each firm.</p>
<p>First, we will create two counterfactual datasets: one where every firm’s <code>iscustomer</code> value is set to 0 (non-customer scenario) and one where every firm’s <code>iscustomer</code> value is set to 1 (customer scenario). Then, we will use our fitted model to predict the expected number of patents for every firm under each counterfactual scenario, producing two vectors of predicted counts: <span class="math inline">\(\hat{y}_0\)</span> for the non-customer scenario and <span class="math inline">\(\hat{y}_1\)</span> for the customer scenario. Finally, we will compute the average difference between these two vectors, <span class="math inline">\(\hat{y}_1 - \hat{y}_0\)</span>, to estimate the average effect of being a Blueprinty customer on patent counts.</p>
<div id="03d8b9be" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated average effect of being a Blueprinty customer on patent counts: 0.79</code></pre>
</div>
</div>
<section id="our-results" class="level3">
<h3 class="anchored" data-anchor-id="our-results">Our Results</h3>
<p>We can see that the estimated average effect of being a Blueprinty customer on patent counts is approximately 0.79 additional patents, holding age and region fixed at their observed values for each firm. This suggests that, on average, firms that are customers of Blueprinty’s software have about 0.79 more patents than they would if they were not customers, after controlling for age and regional differences. This privdes evidence consistent with Blueprinty’s marketing claim that their software is associated with higher patent counts. However, it is important to note that this analysis is based on observational data, and we cannot rule out the possibility of unobserved confounding factors that differ between customers and non-customers and could also drive patent counts. Therefore, while our findings are suggestive of a positive association between using Blueprinty’s software and having more patents, we cannot make a definitive causal claim based on this analysis alone.</p>
<!-- ::: {.callout-note}
- The coefficients from a Poisson regression are not directly interpretable as "additional patents" because the model is multiplicative in $\lambda$, not additive. To get a more interpretable answer, construct two counterfactual datasets:

    1. $X_0$: a copy of your $X$ matrix where every firm's `iscustomer` value is set to 0.
    2. $X_1$: a copy of your $X$ matrix where every firm's `iscustomer` value is set to 1.

- Use your fitted model to predict the expected number of patents for every firm under each counterfactual, producing two vectors $\hat{y}_0$ and $\hat{y}_1$. -->
<!-- - Compute the average of $\hat{y}_1 - \hat{y}_0$. This is your estimate of the average effect of being a Blueprinty customer, holding age and region fixed at their observed values for each firm. -->
<!-- - Report the result and interpret it for the reader. Conclude with a careful statement about what the analysis does and does not establish: it provides evidence consistent with Blueprinty's marketing claim, but because this is an observational study (not a randomized experiment), we cannot rule out unobserved characteristics that differ between customers and non-customers and could also drive patent counts.
::: -->
</section>
</section>
<section id="key-takeaways" class="level1">
<h1>Key Takeaways</h1>
<ul>
<li>The Poisson distribution is a natural choice for modeling count data, such as the number of patents awarded to firms, because it is defined for non-negative integers and has the property that its mean is equal to its variance.</li>
<li>The log-likelihood function for a Poisson model can be derived from the probability mass function, and the MLE for the rate parameter <span class="math inline">\(\lambda\)</span> is the sample mean of the observed counts.</li>
<li>Poisson regression allows us to model the expected count as a function of covariates, and the coefficients can be interpreted in terms of log changes in the expected count.</li>
<li>When interpreting the results of a Poisson regression, it is important to consider the signs and magnitudes of the coefficients, as well as the potential for confounding factors in observational data. While we may find an association between being a customer of Blueprinty’s software and having more patents, we cannot make a definitive causal claim without ruling out the possibility of unobserved confounders.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>