project:
  type: website
  output-dir: docs


website:
  title: "Sophia Salas"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: quotes.qmd
        text: Quotes
    page-footer:
      background: "#f8f9fa"
      left: Copyright 2026, Sophia Salas
format:
  html:
    theme: custom.scss
    toc: true
