<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sophia Salas">
<meta name="dcterms.date" content="2026-05-27">

<title>MaxDiff Analysis of MSBA Class Preferences – Sophia Salas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b9729af4fc7702d2683b6aca8683021a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sophia Salas</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../quotes.html"> 
<span class="menu-text">Quotes</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#counts-analysis" id="toc-counts-analysis" class="nav-link" data-scroll-target="#counts-analysis">Counts Analysis</a>
  <ul class="collapse">
  <li><a href="#bootstrapping" id="toc-bootstrapping" class="nav-link" data-scroll-target="#bootstrapping">Bootstrapping</a></li>
  <li><a href="#analyzing-our-visualization" id="toc-analyzing-our-visualization" class="nav-link" data-scroll-target="#analyzing-our-visualization">Analyzing Our Visualization</a></li>
  </ul></li>
  <li><a href="#from-maxdiff-data-to-mnl-choices" id="toc-from-maxdiff-data-to-mnl-choices" class="nav-link" data-scroll-target="#from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</a></li>
  <li><a href="#mnl-via-maximum-likelihood" id="toc-mnl-via-maximum-likelihood" class="nav-link" data-scroll-target="#mnl-via-maximum-likelihood">MNL via Maximum Likelihood</a>
  <ul class="collapse">
  <li><a href="#coding-our-log-likelihood-function" id="toc-coding-our-log-likelihood-function" class="nav-link" data-scroll-target="#coding-our-log-likelihood-function">Coding Our Log-Likelihood Function</a></li>
  <li><a href="#converting-beta-coefficients-to-shares-of-preference" id="toc-converting-beta-coefficients-to-shares-of-preference" class="nav-link" data-scroll-target="#converting-beta-coefficients-to-shares-of-preference">Converting Beta Coefficients to Shares of Preference</a></li>
  <li><a href="#analyzing-our-mle-results" id="toc-analyzing-our-mle-results" class="nav-link" data-scroll-target="#analyzing-our-mle-results">Analyzing Our MLE Results</a></li>
  </ul></li>
  <li><a href="#mnl-via-bayesian-estimation" id="toc-mnl-via-bayesian-estimation" class="nav-link" data-scroll-target="#mnl-via-bayesian-estimation">MNL via Bayesian Estimation</a></li>
  <li><a href="#random-walk-metropolis-hastings-sampler" id="toc-random-walk-metropolis-hastings-sampler" class="nav-link" data-scroll-target="#random-walk-metropolis-hastings-sampler">Random Walk Metropolis-Hastings Sampler</a></li>
  <li><a href="#item-posterior-mean-beta-and-posterior-shares-of-preference" id="toc-item-posterior-mean-beta-and-posterior-shares-of-preference" class="nav-link" data-scroll-target="#item-posterior-mean-beta-and-posterior-shares-of-preference">Item, Posterior Mean Beta, and Posterior Shares of Preference</a></li>
  <li><a href="#comparing-the-three-methods" id="toc-comparing-the-three-methods" class="nav-link" data-scroll-target="#comparing-the-three-methods">Comparing the Three Methods</a></li>
  <li><a href="#a-word-on-the-comparison" id="toc-a-word-on-the-comparison" class="nav-link" data-scroll-target="#a-word-on-the-comparison">A Word on The Comparison</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MaxDiff Analysis of MSBA Class Preferences</h1>
<p class="subtitle lead">Counts, MLE, and Bayesian Estimation of the MNL model</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sophia Salas </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 27, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p><strong>MaxDiff</strong>, a survey methodology often used in marketing, also known as <strong>Best-Worst Scaling</strong>. In marketing, it can be used to measure the relative importance of different attributes, as a form of A/B testing in which effectiveness of product claims or advertising messages can be tested, and to compare different package designs. It involves survey respondents repeatedly choosing their most and least preferred items from small subsets.</p>
<p>For example, we can see here attributes of smartphone preferences, in which respondents pick the most preferred and least preferred attribute from a set of six. <img src="maxdiff.png" class="img-fluid" alt="MaxDiff"> A respondent will see a screen similar to this multiple times, with different combinations of attributes. By analyzing these choices, we can infer the relative importance of each attribute to the respondents.</p>
<p>We use MaxDiff rather than a 1-10 scale because of human psychology. Humans are good at making trade-offs — picking a best and a worst — but unreliable at calibrating numeric scales. MaxDiff forces real differentiation between items and avoids scale-use bias.</p>
<p>This post analyzes MaxDiff data on MSBA class preferences using three methods: a simple counts analysis, MNL estimation by maximum likelihood, and MNL estimation by Bayesian methods. We’ll compare the results to understand how each method quantifies preference and uncertainty.</p>
<p>Let’s make a prediction about what we might see before we get into it. The three methods should agree on the broad ranking of classes because they are all analyzing the same underlying choice data. However, they will differ in how they quantify the strength of preference and in how they communicate uncertainty because they make different assumptions and use different approaches to estimate the parameters. The counts analysis will give us a quick descriptive summary, the MLE MNL will provide rigorous point estimates with classical standard errors, and the Bayesian MNL will allow us to easily compute credible intervals on derived quantities like shares of preference.</p>
<!-- ::: {.callout-note}
Write a short introduction for the reader that sets the scene. Cover the following points in your own words:

- [**MaxDiff**]{.text-magenta} (also called *Best-Worst Scaling*) is a survey methodology for measuring how strongly people prefer one item over another. On each screen of the survey, the respondent sees a small subset of items (here, 4) and selects the *most-preferred* and *least-preferred* item from that subset. They repeat this over many screens.

- Why MaxDiff (and not, e.g., a 1–10 rating scale)? Humans are good at *trade-offs* — picking a best and a worst — but unreliable at calibrating numeric scales. MaxDiff forces real differentiation between items and avoids scale-use bias. *(See the week-4 "MaxDiff" deck for more.)*

- In this assignment, the 10 items are the 10 core MSBA classes at UCSD Rady. The goal is to estimate students' relative preference for each class using three different methods, and to compare what each tells us:

    1. A simple [**counts analysis**]{.text-magenta} — % times each class was picked best, minus % times picked worst
    2. The [**multinomial logit (MNL)**]{.text-magenta} model fit by [**maximum likelihood**]{.text-magenta} *(see week-5 conjoint/MNL deck for derivation and `optim()` recipe)*
    3. The same MNL model fit by [**Bayesian methods**]{.text-magenta} via Metropolis-Hastings *(see the week-7 deck on Bayesian inference and MCMC)*

- Briefly preview what you expect: the three methods should agree on the broad ranking of classes; they will differ in how they quantify the strength of preference and in how they communicate uncertainty.
::: -->
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>Now let’s dive into the data. The MaxDiff survey collected responses from MSBA students about their preferences for the 10 core classes. Each respondent was shown multiple screens, each containing a subset of 4 classes, and asked to pick the most and least preferred class from that subset.</p>
<section id="exploring-our-data" class="level4">
<h4 class="anchored" data-anchor-id="exploring-our-data">Exploring Our Data</h4>
<p>We have columns in our dataset:</p>
<ul>
<li><code>Record ID</code>: an anonymized identifier for each respondent</li>
<li><code>Task</code>: the screen number for that respondent</li>
<li><code>Position</code>: the slot (1–4) on the screen where the item was shown</li>
<li><code>Item</code>: which of the 10 classes is in that slot</li>
<li><code>Response</code>: <code>1</code> if this item was picked <em>best</em>, <code>-1</code> if picked <em>worst</em>, <code>0</code> otherwise</li>
</ul>
<div id="c01c4139" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>Number of respondents (N): 85
Average tasks per respondent (T): 8.0
Average items per task (J): 4.0
Total unique items in the study: 10</code></pre>
</div>
</div>
<p>We will also run some sanity checks to ensure that our data structure and survey structure is not faulty. We do this by ensuring every task has exactly one row with <code>Response = 1</code> (the “best” pick), exactly one row with <code>Response = -1</code> (the “worst” pick), and the remaining rows with <code>Response = 0</code>. This is a fundamental property of MaxDiff survey data, and if it fails, it indicates a problem with the data collection or processing.</p>
<div id="53aac7ab" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>checks <span class="op">=</span> design_choices.groupby([<span class="st">'Record ID'</span>, <span class="st">'Task'</span>])[<span class="st">'Response'</span>].agg(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    best_count<span class="op">=</span><span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="dv">1</span>).<span class="bu">sum</span>(),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    worst_count<span class="op">=</span><span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>).<span class="bu">sum</span>(),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    zero_count<span class="op">=</span><span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="dv">0</span>).<span class="bu">sum</span>()</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>).reset_index()</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>ok <span class="op">=</span> (checks[<span class="st">'best_count'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (checks[<span class="st">'worst_count'</span>] <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sanity check passed"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sanity check passed</code></pre>
</div>
</div>
<p>We must not forget one of the key properties of MaxDiff designs: they balance exposure. This means that each item should be shown roughly the same number of times across the entire study. Here we can report how many times each of the 10 items was shown to respondents, which should be approximately equal for all items if the design is balanced.</p>
<div id="432c3e4f" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">times_shown</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>273</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>274</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>272</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>276</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>270</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>267</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>276</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>272</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>274</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>266</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<!-- ::: {.callout-note}
- Read in `maxdiff_design_and_choices.csv`. The columns are:

    - `Record ID` — anonymized respondent identifier
    - `Task` — screen number for that respondent
    - `Position` — slot (1–4) on the screen
    - `Item` — which of the 10 classes is in that slot
    - `Response` — `1` if this item was picked *best*, `-1` if picked *worst*, `0` otherwise

- Read in `maxdiff_item_labels.csv` to map item numbers to class names. -->
<!--
- Report basic descriptives: number of respondents ($N$), tasks per respondent ($T$), items per task ($J$ — should be 4), and total items in the study (should be 10). -->
<!-- - Verify the data structure with a sanity check: every task should have exactly one row with `Response = 1` (the "best" pick), exactly one row with `Response = -1` (the "worst" pick), and the remaining rows with `Response = 0`. Code this check. -->
<!--
- Also report how many times each of the 10 items was *shown* across the entire study. Because MaxDiff designs balance exposure, these counts should all be roughly equal.
::: -->
</section>
</section>
<section id="counts-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counts-analysis">Counts Analysis</h2>
<section id="what-is-the-counts-analysis" class="level4">
<h4 class="anchored" data-anchor-id="what-is-the-counts-analysis">What is the Counts Analysis?</h4>
<p>The <strong>counts analysis</strong> is a simple descriptive method to summarize the MaxDiff survey data. For each item, we calculate the percentage of times it was picked as <em>best</em> and the percentage of times it was picked as <em>worst</em> out of the number of times it was shown. The difference between these two percentages gives us a score for each item: <span class="math display">\[
\text{score}_j = \%\text{best}_j - \%\text{worst}_j
\]</span></p>
<p>A large positive score indicates that the item is almost always picked as best when shown, while a negative score indicates that it is almost always picked as worst. A score near 0 suggests that the item is polarizing or middle-of-the-pack.</p>
<div id="1cfe812d" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">times_shown</th>
<th data-quarto-table-cell-role="th">times_best</th>
<th data-quarto-table-cell-role="th">times_worst</th>
<th data-quarto-table-cell-role="th">pct_best</th>
<th data-quarto-table-cell-role="th">pct_worst</th>
<th data-quarto-table-cell-role="th">counts_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>274</td>
<td>147</td>
<td>12</td>
<td>53.65</td>
<td>4.38</td>
<td>49.27</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>270</td>
<td>93</td>
<td>55</td>
<td>34.44</td>
<td>20.37</td>
<td>14.07</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>276</td>
<td>104</td>
<td>71</td>
<td>37.68</td>
<td>25.72</td>
<td>11.96</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>276</td>
<td>77</td>
<td>60</td>
<td>27.90</td>
<td>21.74</td>
<td>6.16</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>272</td>
<td>72</td>
<td>69</td>
<td>26.47</td>
<td>25.37</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>274</td>
<td>55</td>
<td>56</td>
<td>20.07</td>
<td>20.44</td>
<td>-0.36</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>266</td>
<td>23</td>
<td>55</td>
<td>8.65</td>
<td>20.68</td>
<td>-12.03</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>273</td>
<td>33</td>
<td>90</td>
<td>12.09</td>
<td>32.97</td>
<td>-20.88</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>272</td>
<td>43</td>
<td>101</td>
<td>15.81</td>
<td>37.13</td>
<td>-21.32</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>267</td>
<td>33</td>
<td>111</td>
<td>12.36</td>
<td>41.57</td>
<td>-29.21</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Now, let’s visualize these scores in a horizontal bar chart, sorted from highest to lowest. Each bar will be labeled with the class name for clarity.</p>
<div id="378c4162" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-7-output-1.png" width="946" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bootstrapping" class="level3">
<h3 class="anchored" data-anchor-id="bootstrapping">Bootstrapping</h3>
<p>Let’s add 95% bootstrap confidence intervals to the scores. We will resample respondents with replacement, recompute the score for each item, repeat this process around 1,000 times, and then take the 2.5th and 97.5th percentiles to get our confidence intervals.</p>
<div id="5ff33623" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-9-output-1.png" width="998" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analyzing-our-visualization" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-our-visualization">Analyzing Our Visualization</h3>
<p>The most preferred class is the one with the highest counts score, which indicates that it was picked as best more often than it was picked as worst. Our winner is MGTA 495, Marketing Analytics, with Professor Yavorksy. Conversely, the least preferred class is the one with the lowest counts score, indicating that it was picked as worst more often than it was picked as best. MGTA 444, Analytics Consulting has found itself here. The confidence intervals can help us understand the uncertainty around these scores and whether the differences between classes are statistically significant. With the most preferred class, we see a short confidence interval towards the left of bar, indicating that it is consistently preferred across bootstrap samples. The least preferred class has a confidence interval, that, while not as extremely shifted towards the left, is still mostly on the negative side, suggesting that it is consistently less preferred.</p>
<!-- ::: {.callout-note}
- Write a short paragraph explaining the *counts analysis* to the reader. The idea: for each item $j$, compute the percentage of times it was picked as *best* (out of the number of times it was shown), and the percentage of times it was picked as *worst*. The difference is a simple score:

$$
\text{score}_j \;=\; \%\text{best}_j \;-\; \%\text{worst}_j
$$

A score near +1 means an item is almost always picked as best when shown; near -1 means it's almost always picked as worst; near 0 means it's polarizing or middle-of-the-pack. -->
<!-- - Compute the counts score for each of the 10 items. Display a [**ranked table**]{.text-blue} with columns: item, item label, times shown, times best, times worst, % best, % worst, score. -->
<!-- - Plot the scores in a horizontal bar chart, sorted from highest to lowest. Label each bar with the class name (or its abbreviated form). -->
<!-- - Optional but recommended: add 95% bootstrap confidence intervals to the scores. Resample respondents (with replacement), recompute the score for each item, repeat ~1,000 times, and take the 2.5th and 97.5th percentiles. Overlay these CIs on your bar chart. -->
<!--
- After the plot, write a few sentences describing what you observe. Which classes are most preferred? Which are least? Any surprises?
::: -->
</section>
</section>
<section id="from-maxdiff-data-to-mnl-choices" class="level2">
<h2 class="anchored" data-anchor-id="from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</h2>
<p>Now we are going to get into MNL, or the multinomial logit model. This is a more rigorous way to analyze MaxDiff data, as it models the choice process explicitly and allows us to estimate utility coefficients for each item.</p>
<p>But before we get into the estimation, let’s explain how the MaxDiff survey data converts into MNL choice observations. In a MaxDiff survey, each task presents a respondent with a subset of items (in our case, 4 classes) and asks them to pick the most preferred and least preferred item. This can be thought of as two separate choice observations for the MNL model: 1. The first observation is the choice of the best item from the full set of shown items. This is modeled using the soft-max function, where the probability of picking item <span class="math inline">\(b\)</span> as best is given by: <span class="math display">\[
P(\text{best} = b) \;=\; \frac{\exp(\beta_b)}{\exp(\beta_a) + \exp(\beta_b) + \exp(\beta_c) + \exp(\beta_d)}
\]</span> 2. The second observation is the choice of the worst item from the remaining items after the best item has been removed. This is also modeled using a soft-max function, but with the utilities flipped (since we are modeling the worst choice): <span class="math display">\[
P(\text{worst} = c \mid \text{best} = b) \;=\; \frac{\exp(-\beta_c)}{\exp(-\beta_a) + \exp(-\beta_c) + \exp(-\beta_d)}
\]</span> So each task gives us two MNL observations: one for the best pick from the full set, and one for the worst pick from the remaining set. This allows us to use all the information from the MaxDiff survey to estimate the utility coefficients for each item.</p>
<p>The MNL model assigns each item <span class="math inline">\(j\)</span> a utility coefficient <span class="math inline">\(\beta_j\)</span>, which represents the relative preference for that item. However, the soft-max function is invariant to adding a constant to all <span class="math inline">\(\beta\)</span> coefficients, which means that only <span class="math inline">\(J - 1\)</span> of the coefficients are identified. To address this issue of <strong>identifiability</strong>, we can fix one of the coefficients as a reference point. For example, we can set <span class="math inline">\(\beta_1 = 0\)</span> and estimate the remaining coefficients <span class="math inline">\(\beta_2, \ldots, \beta_{10}\)</span>. This normalization allows us to interpret the estimated coefficients as relative preferences compared to the reference item.</p>
<p>Let’s reshape the data into a form that is convenient for the likelihood function. One workable structure is to create a dataset where each row corresponds to a task, and we have columns for the 4 item numbers shown, which one was picked as best, and which one was picked as worst. This way, we can easily iterate over tasks in the likelihood function when we fit the MNL model. For each task, store the 4 item numbers, which one was picked best, and which one was picked worst. You’ll iterate over tasks in the likelihood function.</p>
<div id="5b6f4c5e" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Record ID</th>
<th data-quarto-table-cell-role="th">Task</th>
<th data-quarto-table-cell-role="th">items_shown</th>
<th data-quarto-table-cell-role="th">best_item</th>
<th data-quarto-table-cell-role="th">worst_item</th>
<th data-quarto-table-cell-role="th">remaining_after_best</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>[5, 7, 4, 1]</td>
<td>7</td>
<td>1</td>
<td>[5, 4, 1]</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>2</td>
<td>[8, 3, 10, 9]</td>
<td>10</td>
<td>8</td>
<td>[8, 3, 9]</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>3</td>
<td>[3, 5, 2, 6]</td>
<td>2</td>
<td>6</td>
<td>[3, 5, 6]</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>4</td>
<td>[6, 4, 8, 7]</td>
<td>7</td>
<td>6</td>
<td>[6, 4, 8]</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>5</td>
<td>[2, 9, 7, 1]</td>
<td>2</td>
<td>1</td>
<td>[9, 7, 1]</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<!--
::: {.callout-note}
- Before fitting an MNL, explain to the reader how the MaxDiff survey data converts into [**MNL choice observations**]{.text-magenta}. Reference the conjoint/MNL slides from week 5.

- The MNL model assigns each item $j$ a utility coefficient $\beta_j$. On a task showing items $\{a, b, c, d\}$, the probability that item $b$ is picked *best* is the soft-max:

$$
P(\text{best} = b) \;=\; \frac{\exp(\beta_b)}{\exp(\beta_a) + \exp(\beta_b) + \exp(\beta_c) + \exp(\beta_d)}
$$

- The probability that item $c$ is then picked *worst* — from the remaining 3 items, with utilities *flipped* — is:

$$
P(\text{worst} = c \mid \text{best} = b) \;=\; \frac{\exp(-\beta_c)}{\exp(-\beta_a) + \exp(-\beta_c) + \exp(-\beta_d)}
$$

So each task gives [*two*]{.text-blue} MNL observations: the best-pick from the full set, and the worst-pick from the remaining set.

- [**Identifiability**]{.text-magenta}: the soft-max is invariant to adding a constant to every $\beta$, so only $J - 1 = 9$ of the 10 coefficients are identified. Fix one as the reference — for example, set $\beta_1 = 0$ and estimate $\beta_2, \ldots, \beta_{10}$. Mention this normalization to the reader. -->
<!-- - Reshape the data into a form convenient for the likelihood. One workable structure: for each task, store the 4 item numbers, which one was picked best, and which one was picked worst. You'll iterate over tasks in the likelihood function.
::: -->
</section>
<section id="mnl-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-maximum-likelihood">MNL via Maximum Likelihood</h2>
<p>It’s Likelihood time! Now that we have our data structured for MNL estimation, we can write down the log-likelihood function and maximize it to get our estimates of the <span class="math inline">\(\beta\)</span> coefficients.</p>
<p>Our log-likelihood function sums over all tasks, accounting for both the best and worst choices. For each task, we have a contribution from the best pick and a contribution from the worst pick. The log-likelihood can be expressed as: <span class="math display">\[
\ell(\boldsymbol{\beta}) \;=\; \sum_{\text{tasks}} \Big[\, \beta_{j^*_b} \;-\; \log \!\!\!\sum_{j \in \text{shown}}\!\!\! \exp(\beta_j) \;-\; \beta_{j^*_w} \;-\; \log \!\!\!\!\!\sum_{j \in \text{shown} \setminus \{j^*_b\}}\!\!\!\! \exp(-\beta_j) \,\Big]
\]</span> where <span class="math inline">\(j^*_b\)</span> is the item picked best in that task and <span class="math inline">\(j^*_w\)</span> is the item picked worst.</p>
<section id="coding-our-log-likelihood-function" class="level3">
<h3 class="anchored" data-anchor-id="coding-our-log-likelihood-function">Coding Our Log-Likelihood Function</h3>
<div id="7c904bdb" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> expand_beta(theta):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Map the 9 free parameters into a beta vector indexed by item number.</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Item 1 is fixed to zero for identification.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> np.zeros(num_items <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    beta[<span class="dv">1</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    beta[<span class="dv">2</span>:] <span class="op">=</span> theta</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> beta</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_likelihood(theta):</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> expand_beta(theta)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    best_part <span class="op">=</span> beta[best_items] <span class="op">-</span> logsumexp(beta[items_matrix], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    worst_part <span class="op">=</span> <span class="op">-</span>beta[worst_items] <span class="op">-</span> logsumexp(<span class="op">-</span>beta[remaining_matrix], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(best_part <span class="op">+</span> worst_part)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_log_likelihood(theta):</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>log_likelihood(theta)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="08df950a" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Optimization message: </span><span class="sc">{</span>mle_out<span class="sc">.</span>message<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Final log-likelihood: </span><span class="sc">{</span>log_likelihood(theta_hat)<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization message: Desired error not necessarily achieved due to precision loss.
Final log-likelihood: -1572.731</code></pre>
</div>
</div>
<p>The optimizer may report precision-loss warnings because the likelihood surface is fairly flat in some directions, but the solution is stable and the finite-difference Hessian below is positive definite.</p>
</section>
<section id="converting-beta-coefficients-to-shares-of-preference" class="level3">
<h3 class="anchored" data-anchor-id="converting-beta-coefficients-to-shares-of-preference">Converting Beta Coefficients to Shares of Preference</h3>
<p>To make the <span class="math inline">\(\hat\beta\)</span> coefficients more interpretable, we can convert them into shares of preference using the soft-max function: <span class="math display">\[
\hat s_j \;=\; \frac{\exp(\hat\beta_j)}{\sum_{k=1}^{10} \exp(\hat\beta_k)}
\]</span></p>
<p>It is much easier to understand the shares than the raw <span class="math inline">\(\beta\)</span> coefficients, as they sum to 1 across items and directly answer the question: “if all 10 classes were on a single screen, what fraction of choices would each one get?”</p>
<div id="4b5cb8bd" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># converting to shares</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>mle_shares <span class="op">=</span> np.exp(beta_hat_full[<span class="dv">1</span>:]) <span class="op">/</span> np.exp(beta_hat_full[<span class="dv">1</span>:]).<span class="bu">sum</span>()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>mle_results <span class="op">=</span> pd.DataFrame({</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Item"</span>: item_ids,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Class"</span>: [item_labels_dict[i] <span class="cf">for</span> i <span class="kw">in</span> item_ids],</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"beta_hat"</span>: beta_hat_full[<span class="dv">1</span>:],</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"se"</span>: se_full,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"mle_share"</span>: mle_shares</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>mle_results.sort_values(<span class="st">"mle_share"</span>, ascending<span class="op">=</span><span class="va">False</span>).<span class="bu">round</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">beta_hat</th>
<th data-quarto-table-cell-role="th">se</th>
<th data-quarto-table-cell-role="th">mle_share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1.6298</td>
<td>0.1462</td>
<td>0.2839</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.7445</td>
<td>0.1418</td>
<td>0.1171</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.6563</td>
<td>0.1424</td>
<td>0.1072</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.5553</td>
<td>0.1399</td>
<td>0.0969</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.4433</td>
<td>0.1397</td>
<td>0.0867</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.4380</td>
<td>0.1373</td>
<td>0.0862</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.2359</td>
<td>0.1370</td>
<td>0.0704</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>0.0000</td>
<td>0.0000</td>
<td>0.0556</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.0666</td>
<td>0.1395</td>
<td>0.0520</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.2388</td>
<td>0.1406</td>
<td>0.0438</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="analyzing-our-mle-results" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-our-mle-results">Analyzing Our MLE Results</h3>
<p>We can now look at the estimated <span class="math inline">\(\hat\beta\)</span> coefficients, their standard errors, and the derived shares of preference. The <span class="math inline">\(\hat\beta\)</span> coefficients represent the relative utility of each class compared to the reference class (the one with <span class="math inline">\(\beta_1 = 0\)</span>). A higher <span class="math inline">\(\hat\beta\)</span> indicates a stronger preference for that class. The standard errors give us a sense of the uncertainty around these estimates. The shares of preference, derived from the <span class="math inline">\(\hat\beta\)</span> coefficients, provide a more intuitive interpretation of the results, showing the proportion of choices each class would receive if they were all presented together.</p>
<div id="b6e2326b" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-17-output-1.png" width="946" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The MLE ranking is essentially the same as the counts ranking. <strong>MGTA 495 Marketing Analytics</strong> is still clearly the most preferred class, with an estimated share of preference around 28%. The next group is <strong>MGTA 453 Business Analytics</strong> and <strong>MGTA 455 Customer Analytics</strong>. The lowest share belongs to <strong>MGTA 444 Analytics Consulting</strong>. The MNL model adds structure by modeling both chosen and non-chosen alternatives within each task, rather than only counting best and worst selections.</p>
<!--
::: {.callout-note}
- Write down the log-likelihood. Summing over $N \cdot T$ tasks:

$$
\ell(\boldsymbol{\beta}) \;=\; \sum_{\text{tasks}} \Big[\, \beta_{j^*_b} \;-\; \log \!\!\!\sum_{j \in \text{shown}}\!\!\! \exp(\beta_j) \;-\; \beta_{j^*_w} \;-\; \log \!\!\!\!\!\sum_{j \in \text{shown} \setminus \{j^*_b\}}\!\!\!\! \exp(-\beta_j) \,\Big]
$$

where $j^*_b$ is the item picked best in that task and $j^*_w$ is the item picked worst. -->
<!-- - Code the log-likelihood as a function `ll(beta, ...)` where `beta` is a vector of length 9 (or 10, with $\beta_1$ pinned to 0 inside the function). Use log-sum-exp form (`v - log(rowSums(exp(v)))`) for numerical stability — see the week-5 slides on fitting MNL by hand.

- Maximize the log-likelihood. In R:

```r
out <- optim(par = rep(0, 9), fn = ll, ...,
             method = "BFGS", hessian = TRUE,
             control = list(fnscale = -1))
``` -->
<!-- - Report the estimated $\hat{\boldsymbol{\beta}}$ and standard errors. SEs come from the inverse of the negative Hessian:

```r
se <- sqrt(diag(solve(-out$hessian)))
```

- Convert the $\hat\beta$'s into [**shares of preference**]{.text-blue} for interpretability:$$
\hat s_j \;=\; \frac{\exp(\hat\beta_j)}{\sum_{k=1}^{10} \exp(\hat\beta_k)}$$ -->
<!-- These shares are easier to read than raw $\beta$'s — they sum to 1 across items and answer the question, *"if all 10 classes were on a single screen, what fraction of choices would each one get?"* -->
<!--
- Display a table of items with $\hat\beta_j$, $SE(\hat\beta_j)$, and $\hat s_j$. Plot the shares in a horizontal bar chart, sorted from highest to lowest.

- Compare the MLE ranking to the counts ranking from the previous section. Are they identical? Where do they differ? Write a few sentences explaining. -->
<!-- ::: -->
</section>
</section>
<section id="mnl-via-bayesian-estimation" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-bayesian-estimation">MNL via Bayesian Estimation</h2>
<p>We can fit the same MNL model using Bayesian methods instead of maximum likelihood. <strong>Bayesian estimation</strong> allows us to compute the full posterior distribution over the <span class="math inline">\(\beta\)</span> coefficients, which gives us a richer understanding of uncertainty compared to point estimates and standard errors from MLE.</p>
<p>The posterior distribution over <span class="math inline">\(\boldsymbol{\beta}\)</span> is given by Bayes’ rule: <span class="math display">\[
\pi(\boldsymbol{\beta} \mid \boldsymbol{y}) \;\propto\; L(\boldsymbol{\beta}) \cdot \pi(\boldsymbol{\beta})
\]</span> where <span class="math inline">\(L(\boldsymbol{\beta})\)</span> is the likelihood function we defined earlier, and <span class="math inline">\(\pi(\boldsymbol{\beta})\)</span> is the prior distribution over the parameters.</p>
<p>For our prior, we will use a weakly informative multivariate normal distribution: <span class="math inline">\(\boldsymbol{\beta} \sim N(\boldsymbol{0},\; 10 \cdot I)\)</span>. This means that each <span class="math inline">\(\beta_j\)</span> has a mean of 0 and a standard deviation of <span class="math inline">\(\sqrt{10} \approx 3.2\)</span>, which is diffuse enough to allow the data to speak while still providing some regularization.</p>
</section>
<section id="random-walk-metropolis-hastings-sampler" class="level2">
<h2 class="anchored" data-anchor-id="random-walk-metropolis-hastings-sampler">Random Walk Metropolis-Hastings Sampler</h2>
<p>To sample from the posterior distribution, we can implement a random-walk Metropolis-Hastings sampler. We will run the sampler for around 20,000 iterations, discarding the first 25% as burn-in. We will also tune the step size to achieve an acceptance rate of roughly 25–40%.</p>
<div id="8a75f0e2" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_posterior(theta):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    prior_sd <span class="op">=</span> np.sqrt(<span class="dv">10</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    log_prior <span class="op">=</span> np.<span class="bu">sum</span>(<span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> (theta <span class="op">/</span> prior_sd) <span class="op">**</span> <span class="dv">2</span> <span class="op">-</span> np.log(prior_sd <span class="op">*</span> np.sqrt(<span class="dv">2</span> <span class="op">*</span> np.pi)))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> log_likelihood(theta) <span class="op">+</span> log_prior</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> metropolis_hastings(theta0, n_iter<span class="op">=</span><span class="dv">20000</span>, step<span class="op">=</span><span class="fl">0.08</span>, seed<span class="op">=</span><span class="dv">123</span>):</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    K <span class="op">=</span> <span class="bu">len</span>(theta0)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    draws <span class="op">=</span> np.zeros((n_iter, K))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> theta0.copy()</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    lp <span class="op">=</span> log_posterior(theta)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    accept <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(n_iter):</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>        theta_star <span class="op">=</span> theta <span class="op">+</span> rng.normal(<span class="dv">0</span>, step, K)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>        lp_star <span class="op">=</span> log_posterior(theta_star)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> np.log(rng.uniform()) <span class="op">&lt;</span> lp_star <span class="op">-</span> lp:</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>            theta <span class="op">=</span> theta_star</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>            lp <span class="op">=</span> lp_star</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>            accept <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>        draws[t, :] <span class="op">=</span> theta</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> draws, accept <span class="op">/</span> n_iter</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="b87bbcb0" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The step size was tuned to give an acceptance rate in the target range.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>draws, accept_rate <span class="op">=</span> metropolis_hastings(theta_hat, n_iter<span class="op">=</span><span class="dv">20000</span>, step<span class="op">=</span><span class="fl">0.08</span>, seed<span class="op">=</span><span class="dv">123</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can now report the acceptance rate of 28.73%. This is within the target range of 25–40%, indicating that our step size is well-tuned for efficient exploration of the posterior distribution. An acceptance rate that is too low (e.g., below 20%) would suggest that the sampler is proposing moves that are too large, leading to many rejections and slow mixing. Conversely, an acceptance rate that is too high (e.g., above 50%) would indicate that the sampler is proposing moves that are too small, resulting in slow exploration of the parameter space. Our acceptance rate of around 28% suggests a good balance between these extremes, allowing for effective sampling from the posterior distribution.</p>
<div id="2a09d4b2" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Acceptance rate: </span><span class="sc">{</span>accept_rate<span class="sc">:.2%}</span><span class="ss">"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>burn <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.25</span> <span class="op">*</span> <span class="bu">len</span>(draws))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>post_theta <span class="op">=</span> draws[burn:, :]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>post_beta <span class="op">=</span> np.column_stack([np.zeros(post_theta.shape[<span class="dv">0</span>]), post_theta])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Acceptance rate: 28.73%</code></pre>
</div>
</div>
<div id="995995ce" class="cell" data-execution_count="20">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-21-output-1.png" width="950" height="278" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-21-output-2.png" width="950" height="278" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-21-output-3.png" width="950" height="278" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The trace plots look like fuzzy caterpillars after burn-in rather than slow drifting lines. That pattern indicates that the chain is moving around the posterior distribution instead of continuing to search for a new region.</p>
</section>
<section id="item-posterior-mean-beta-and-posterior-shares-of-preference" class="level2">
<h2 class="anchored" data-anchor-id="item-posterior-mean-beta-and-posterior-shares-of-preference">Item, Posterior Mean Beta, and Posterior Shares of Preference</h2>
<div id="ffe65e5c" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">post_mean_beta</th>
<th data-quarto-table-cell-role="th">beta_ci_low</th>
<th data-quarto-table-cell-role="th">beta_ci_high</th>
<th data-quarto-table-cell-role="th">post_mean_share</th>
<th data-quarto-table-cell-role="th">share_ci_low</th>
<th data-quarto-table-cell-role="th">share_ci_high</th>
<th data-quarto-table-cell-role="th">post_std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1.6085</td>
<td>1.3044</td>
<td>1.8954</td>
<td>0.2842</td>
<td>0.2390</td>
<td>0.3307</td>
<td>0.1511</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.7170</td>
<td>0.4333</td>
<td>1.0109</td>
<td>0.1167</td>
<td>0.0957</td>
<td>0.1393</td>
<td>0.1470</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.6366</td>
<td>0.3503</td>
<td>0.9391</td>
<td>0.1077</td>
<td>0.0882</td>
<td>0.1305</td>
<td>0.1481</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.5319</td>
<td>0.2572</td>
<td>0.8146</td>
<td>0.0970</td>
<td>0.0798</td>
<td>0.1167</td>
<td>0.1441</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.4185</td>
<td>0.1294</td>
<td>0.6828</td>
<td>0.0866</td>
<td>0.0711</td>
<td>0.1043</td>
<td>0.1417</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.4099</td>
<td>0.1427</td>
<td>0.6889</td>
<td>0.0858</td>
<td>0.0708</td>
<td>0.1025</td>
<td>0.1408</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.2056</td>
<td>-0.0734</td>
<td>0.4692</td>
<td>0.0700</td>
<td>0.0574</td>
<td>0.0846</td>
<td>0.1396</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>0.0000</td>
<td>0.0000</td>
<td>0.0000</td>
<td>0.0570</td>
<td>0.0459</td>
<td>0.0701</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.0996</td>
<td>-0.3893</td>
<td>0.1798</td>
<td>0.0516</td>
<td>0.0420</td>
<td>0.0631</td>
<td>0.1435</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.2710</td>
<td>-0.5494</td>
<td>0.0123</td>
<td>0.0435</td>
<td>0.0349</td>
<td>0.0531</td>
<td>0.1436</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="2f88146f" class="cell" data-execution_count="22">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-23-output-1.png" width="946" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The Bayesian posterior means are very close to the MLE estimates, which is what we would expect because the prior is weak and the sample provides a lot of information. We also see standard deviations that reflect the uncertainty in the estimates. Posterior beta standard errors are largely similar. We see the biggest differences in the posterior distributions of the beta parameters with Item 5, MGTA 453 in which the Posterior SE is 0.147 and the MLE SE is 0.1418. Standard errors may differ because the MLE SEs are based on a local curvature of the likelihood at the point estimate, while the Bayesian posterior distribution captures uncertainty across the entire parameter space, influenced by both the likelihood and the prior. In cases where the likelihood is relatively flat or has multiple modes, the Bayesian posterior may reflect greater uncertainty than the MLE standard errors suggest.</p>
<p>The biggest advantage of the Bayesian approach is that uncertainty in derived quantities is straightforward: each draw can be transformed into shares of preference, and the credible intervals can be read directly from the resulting distribution.</p>
<!-- ::: {.callout-note}
- Now fit the same MNL model by [**Bayesian methods**]{.text-magenta}. Reference the week-7 slides on Bayes' rule and the random-walk Metropolis-Hastings sampler.

- The posterior over $\boldsymbol{\beta}$ is

$$
\pi(\boldsymbol{\beta} \mid \boldsymbol{y}) \;\propto\; L(\boldsymbol{\beta}) \cdot \pi(\boldsymbol{\beta})
$$

Use a weakly informative multivariate normal prior: $\boldsymbol{\beta} \sim N(\boldsymbol{0},\; 10 \cdot I)$. (SD $\approx 3.2$ on each $\beta$ is plenty diffuse without being absurd.)

- Code a random-walk Metropolis sampler. The skeleton is:

```r
log_post <- function(beta) ll(beta, ...) + sum(dnorm(beta, 0, sqrt(10), log = TRUE))

mh <- function(beta0, n_iter, step) {
  K <- length(beta0)
  draws <- matrix(NA, n_iter, K)
  beta  <- beta0
  lp    <- log_post(beta)
  accept <- 0
  for (t in 1:n_iter) {
    beta_star <- beta + rnorm(K, 0, step)
    lp_star   <- log_post(beta_star)
    if (log(runif(1)) < lp_star - lp) {
      beta <- beta_star; lp <- lp_star; accept <- accept + 1
    }
    draws[t, ] <- beta
  }
  list(draws = draws, accept_rate = accept / n_iter)
}
``` -->
<!-- - Run the sampler for ~20,000 iterations (or more if you have patience). Discard the first 25% as burn-in.

- [**Tune the step size**]{.text-blue} to land at an acceptance rate of roughly 25–40%. If acceptance is too low, halve the step; too high, double it. *(See week-7 "Tuning the Step Size" slide.)* -->
<!-- - Run diagnostics: report the final acceptance rate, plot the trace for at least 2–3 of the $\beta$ parameters (you should see a "fuzzy caterpillar," not a slow drift), and confirm that the chain has stabilized after burn-in. -->
<!-- - Compute and report:

    - Posterior **mean** $\hat\beta_j$ for each item
    - 95% **credible interval** $[2.5\%,\, 97.5\%]$ percentiles of the post-burn-in draws
    - Posterior shares of preference: for each MCMC draw, compute $\hat s_j^{(s)} = \exp(\hat\beta_j^{(s)}) / \sum_k \exp(\hat\beta_k^{(s)})$, then take the posterior mean of the $\hat s_j^{(s)}$ across draws.

- Display a table with item, posterior mean $\beta$, 95% CI, posterior mean share. Plot the shares with the credible interval as error bars.

- Compare to the MLE results: posterior means should be close to the MLE point estimates; posterior SDs should be close to the MLE standard errors. Where do they differ noticeably? Why?
::: -->
</section>
<section id="comparing-the-three-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-three-methods">Comparing the Three Methods</h2>
<p>Now that we have results from all three methods — counts, MLE MNL, and Bayesian MNL — let’s put them side-by-side for comparison. We will create a table that includes the item/class label, counts score, counts rank, MLE share and rank, and Bayesian posterior mean share and rank. We will sort this table by one of the rankings (e.g., MLE rank) to make it easier to compare.</p>
<div id="ebe51f92" class="cell" data-execution_count="23">
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">counts_score</th>
<th data-quarto-table-cell-role="th">counts_rank</th>
<th data-quarto-table-cell-role="th">mle_share</th>
<th data-quarto-table-cell-role="th">mle_rank</th>
<th data-quarto-table-cell-role="th">post_mean_share</th>
<th data-quarto-table-cell-role="th">bayes_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>49.2701</td>
<td>1</td>
<td>0.2839</td>
<td>1</td>
<td>0.2842</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>14.0741</td>
<td>2</td>
<td>0.1171</td>
<td>2</td>
<td>0.1167</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>11.9565</td>
<td>3</td>
<td>0.1072</td>
<td>3</td>
<td>0.1077</td>
<td>3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>6.1594</td>
<td>4</td>
<td>0.0969</td>
<td>4</td>
<td>0.0970</td>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>1.1029</td>
<td>5</td>
<td>0.0867</td>
<td>5</td>
<td>0.0866</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>-0.3650</td>
<td>6</td>
<td>0.0862</td>
<td>6</td>
<td>0.0858</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>-12.0301</td>
<td>7</td>
<td>0.0704</td>
<td>7</td>
<td>0.0700</td>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>-20.8791</td>
<td>8</td>
<td>0.0556</td>
<td>8</td>
<td>0.0570</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-21.3235</td>
<td>9</td>
<td>0.0520</td>
<td>9</td>
<td>0.0516</td>
<td>9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-29.2135</td>
<td>10</td>
<td>0.0438</td>
<td>10</td>
<td>0.0435</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="ece4ddf1" class="cell" data-execution_count="24">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-25-output-1.png" width="1741" height="662" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="a-word-on-the-comparison" class="level2">
<h2 class="anchored" data-anchor-id="a-word-on-the-comparison">A Word on The Comparison</h2>
<p>All three methods agree almost exactly on the ranking. They identify <strong>MGTA 495 Marketing Analytics</strong> as the strongest class by a large margin, followed by <strong>Business Analytics</strong> and <strong>Customer Analytics</strong>. They also agree that <strong>Analytics Consulting</strong>, <strong>Marketing/Finance/Operations</strong>, and <strong>AI Math, Programming, and Analytics</strong> are at the bottom of this particular survey. The agreement is strong because the preference signal is not subtle: the top and bottom items are separated clearly in the data. The disagreement is quite small and mostly in the middle of the ranking, where items have similar utility and small noise can flip their order.</p>
<p>The MNL model adds value over counts because it models the actual choice process. Every item shown in a task contributes information, including items that were not selected as best or worst. This allows the MNL to extract more signal from the data and provide a more nuanced ranking, especially for items in the middle of the pack. The counts method only looks at best and worst picks, while the MNL considers the full set of shown items and their relative utilities.</p>
<p>The Bayesian model adds value over MLE because it makes uncertainty on derived quantities, such as shares of preference, easy to compute. Instead of relying on a delta-method approximation, we can pass every posterior draw through the soft-max formula and summarize the resulting distribution. This allows us to get credible intervals on shares of preference directly from the posterior distribution, which is more accurate and informative than the standard errors from MLE. The Bayesian approach also allows for more flexible modeling, such as hierarchical extensions to estimate individual-level preferences, which would be more complex to implement in a frequentist framework.</p>
<!-- ::: {.callout-note}
- Create a single side-by-side comparison of all three analyses. Suggested format: a table with columns

    - Item / class label
    - Counts score (% best − % worst)
    - Counts rank
    - MLE share of preference, MLE rank
    - Bayes posterior-mean share, Bayes rank

  Sorted by one of the rankings (e.g., MLE rank).

- Also create a visual comparison: three horizontal bar charts side-by-side, one per method, each showing items sorted by that method's score/share. Color-code consistently so the reader can trace a single class across all three panels. -->
<!-- - Write a paragraph discussing the comparison:

    - Where do the three methods *agree*? Almost always at the top and bottom of the ranking.
    - Where do they *disagree* — and why? Often in the middle, where items have similar utility and small noise can flip rankings.
    - What does the MNL add over the counts analysis? *(Hint: it models the choice process explicitly — every "shown" item contributes information about *not* being picked, not just the picks themselves.)*
    - What does Bayes add over MLE? *(Hint: credible intervals on derived quantities like shares of preference are easy — just push every MCMC draw through the soft-max and take quantiles. Doing this from an MLE requires the delta method.)*
::: -->
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>Enough of the technical jargon — let’s step back and synthesize what we found.</p>
<p>The main substantive conclusion is that students in this sample most prefer <strong>MGTA 495 Marketing Analytics</strong>, with a large gap between it and the rest of the classes. <em>I</em>, personally do not find this as a surprise. I may be biased, as I have taken a previous course during my undergraduate studies. But, given that my opinion has not changed since then, I believe the results check out.The next tier contains <strong>MGTA 453 Business Analytics</strong> and <strong>MGTA 455 Customer Analytics</strong>. Again, I do not find this surprising. While Customer Analytics is notorious for being one of the most diffocult classes, it is also agreed upon that it is one of the most valuable to students. The least preferred item in this MaxDiff survey is <strong>MGTA 444 Analytics Consulting</strong>. It is disheartening to see any class ranked last. However, I hypothesis that this might be due to the less technical nature of the course. Or, possibly, in my opinion, a class that would have been very valuable during the quarter of the capstone project.</p>
<p>Methodologically, the three approaches answer slightly different questions. The counts analysis is best for a quick dashboard-style summary because it is simple and transparent. It is also the easiest to interpret and explain to a general audience. The MLE MNL model is better when we want a formal choice model with point estimates, standard errors, and interpretable preference shares. It is most useful when we want a single, definitive answer with uncertainty estimates. The Bayesian MNL model is most useful when we care about uncertainty in simulated or transformed outcomes, such as shares of preference, market simulations, or hypothetical changes to the choice set. The Bayesian approach also allows for more complex extensions, such as hierarchical models to estimate individual-level preferences, which would be more difficult to implement in a frequentist framework.</p>
<p>There are also important caveats. The survey appears to use a self-selected sample of MSBA students, so the results may not generalize to every student in the program or to future cohorts. These students, chose to take this Marketing Analytics course, so seeing that the Marketing Analytics course ranked the highest across models, we might be witnessing a form of selection bias. Additionally, this is a very specific group of students, and because they were not chose randomly, we cannot confidently say that our results would generalize to future cohorts. Preferences could also be affected by when students took the survey, what classes they had already completed, the instructors they knew, and the order in which items appeared.</p>
<p>If I had more time, I would explore how preferences differ by cohort, career interests, or prior exposure to each subject. For example, do students with a background in marketing prefer the Marketing Analytics class more than those with a background in finance? Do students who have already taken certain classes have different preferences for the remaining classes? Do students with more work experience behave and answer differently than students with less experience? Exploring angles such as these, would provide a richer understanding of how preferences vary across different segments of the student population and could inform course offerings and advising strategies in the future.</p>
<!--
::: {.callout-note}
- Close with a short discussion section that synthesizes the analysis for a non-technical reader (think: an academic advisor or a student deciding which classes to take). Cover:

    - The substantive finding — which MSBA classes do students prefer most? Are there any surprises?
    - The methodological finding — for what kind of question would you reach for each of the three methods?

        - *Counts*: quick descriptive summary, useful for an executive dashboard
        - *MLE MNL*: rigorous point estimates with classical standard errors; good when you need a single number to report
        - *Bayesian MNL*: when you want uncertainty on derived quantities (shares, market simulations, "what if we added a new class?" scenarios), or when you want to extend the model hierarchically to estimate individual-level preferences

    - Caveats: the survey was on a self-selected sample of MSBA students; preferences may not generalize beyond this group. Item presentation order, prior coursework, and current standing in the program may all affect responses.

- End with one or two sentences on what you would do differently or explore next if you had more time.
::: -->


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>